# Generated by Django 3.1.2 on 2021-12-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('cod_checkin', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('horario', models.DateField()),
                ('documento', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'check_in',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('cod_checkout', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('horario', models.DateField()),
                ('documento', models.BinaryField(blank=True, null=True)),
                ('multa', models.FloatField()),
                ('multa_monto', models.BigIntegerField()),
            ],
            options={
                'db_table': 'check_out',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('run_cliente', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido_p', models.CharField(max_length=15)),
                ('apellido_m', models.CharField(max_length=15)),
                ('firma', models.BinaryField(blank=True, null=True)),
                ('tipo_usuario', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('cod_conduc', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('run', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('tipo_licencia', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'conductor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('cod_depa', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('num_dormitorios', models.CharField(max_length=15)),
                ('num_banos', models.CharField(max_length=15)),
                ('tipo_depa', models.CharField(max_length=15)),
                ('valor_depaxdia', models.CharField(max_length=15)),
                ('valor_inventario', models.CharField(max_length=15)),
                ('fotos_depa', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('cod_inv', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nom_objeto', models.CharField(max_length=15)),
                ('tipo_objeto', models.CharField(max_length=15)),
                ('estado_objeto', models.CharField(max_length=15)),
                ('valor_objeto', models.BigIntegerField()),
                ('cantidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('cod_mant', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('reparacion', models.FloatField()),
                ('disponibilidad', models.FloatField()),
                ('remodelacion', models.FloatField()),
                ('limpieza', models.FloatField()),
            ],
            options={
                'db_table': 'mantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('tipo_reserva', models.CharField(max_length=15)),
                ('pago_parcial', models.CharField(max_length=30)),
                ('pago_completo', models.CharField(max_length=30)),
                ('pago_aprobado', models.FloatField()),
                ('run', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('cod_serv', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('acondicionado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('cod_tour', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('tipo_tour', models.CharField(max_length=15)),
                ('horario', models.DateField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('cod_transp', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=50)),
                ('horario', models.DateField()),
                ('desde', models.CharField(max_length=50)),
                ('hasta', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('cod_vehi', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('tipo_vehiculo', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('patente', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('cod_zon', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=15)),
                ('comuna', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'zona',
                'managed': False,
            },
        ),
    ]
